import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { PostBar } from "@/components/PostBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen py-16">
          <nav className="flex-grow flex justify-end p-8 pr-12 text-lg border-r">
            <ul>
              <li className="mb-4">
                <Link
                  href="/events"
                  className="font-bold py-2 px-5 rounded hover:bg-amber-200 hover:text-black active:bg-amber-100 transition ease-in-out"
                >
                  Events
                </Link>
              </li>
              <li className="mb-4">
                <Link
                  href="/groups"
                  className="font-bold py-2 px-5 rounded hover:bg-amber-200 hover:text-black active:bg-amber-100 transition ease-in-out"
                >
                  Groups
                </Link>
              </li>
              <li className="mb-4">
                <Link
                  href="/people"
                  className="font-bold py-2 px-5 rounded hover:bg-amber-200 hover:text-black active:bg-amber-100 transition ease-in-out"
                >
                  People
                </Link>
              </li>
              <li>
                <Link
                  href="/profile"
                  className="font-bold py-2 px-5 rounded hover:bg-amber-200 hover:text-black active:bg-amber-100 transition ease-in-out"
                >
                  Profile
                </Link>
              </li>
            </ul>
          </nav>
          <main className="flex-grow px-4 w-1/3 ">
            <div className="px-4 h-full overflow-y-auto">{children}</div>
          </main>
          <PostBar className="border-l" />
        </div>
      </body>
    </html>
  );
}
